project_name: webhookdb
builds:
  - id: webhookdb
    ldflags:
      - -s -w -X github.com/lithictech/webhookdb-cli/config.Version={{.Version}} -X github.com/lithictech/webhookdb-cli/config.BuildSha={{.Commit}} -X github.com/lithictech/webhookdb-cli/config.BuildTime={{.Date}}
    binary: webhookdb
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
    - goos: windows
      goarch: arm64
archives:
  - files:
      - match-nothing-to-keep-archive-binary-only*
    replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  draft: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
signs:
  - artifacts: checksum
brews:
  - tap:
      owner: lithictech
      name: homebrew-webhookdb
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: next
    commit_author:
      name: webhookdbreleaser
      email: webhookdb@lithic.tech
    description: "WebhookDB queries any API in real-time with SQL. More at https://webhookdb.com"
    homepage: "https://webhookdb.com"
    caveats: "❤ Thanks for installing the WebhookDB CLI! Run `webhookdb auth login` to get register or sign in."
